/* =========================================================================
   ICONS LIBRARY
   ========================================================================= */
const ICONS = {
  // Navigation
  home: '<path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/>',
  cart: '<circle cx="9" cy="21" r="1"/><circle cx="20" cy="21" r="1"/><path d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"/>',
  package: '<line x1="16.5" y1="9.4" x2="7.5" y2="4.21"/><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/>',
  users: '<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',
  truck: '<rect x="1" y="3" width="15" height="13"/><polygon points="16 8 20 8 23 11 23 16 16 16 16 8"/><circle cx="5.5" cy="18.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/>',
  wallet: '<path d="M21 12V7H5a2 2 0 0 1 0-4h14v4"/><path d="M3 5v14a2 2 0 0 0 2 2h16v-5"/><path d="M18 12a2 2 0 0 0 0 4h4v-4Z"/>',
  chart: '<line x1="12" y1="20" x2="12" y2="10"/><line x1="18" y1="20" x2="18" y2="4"/><line x1="6" y1="20" x2="6" y2="16"/>',
  settings: '<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"/>',
  database: '<ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/>',
  activity: '<polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/>',
  shield: '<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>',
  store: '<path d="m2 7 2-5h16l2 5M4 7v13h16V7M9 20V12h6v8"/>',
  // Actions
  plus: '<line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>',
  minus: '<line x1="5" y1="12" x2="19" y2="12"/>',
  x: '<line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>',
  check: '<polyline points="20 6 9 17 4 12"/>',
  search: '<circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/>',
  filter: '<polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"/>',
  edit: '<path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/>',
  trash: '<polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/>',
  eye: '<path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/>',
  print: '<polyline points="6 9 6 2 18 2 18 9"/><path d="M6 18H4a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2"/><rect x="6" y="14" width="12" height="8"/>',
  download: '<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>',
  upload: '<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/>',
  save: '<path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"/><polyline points="17 21 17 13 7 13 7 21"/><polyline points="7 3 7 8 15 8"/>',
  refresh: '<polyline points="23 4 23 10 17 10"/><polyline points="1 20 1 14 7 14"/><path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"/>',
  copy: '<rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>',
  // UI
  menu: '<line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="18" x2="21" y2="18"/>',
  bell: '<path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/>',
  moon: '<path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/>',
  sun: '<circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>',
  chevronLeft: '<polyline points="15 18 9 12 15 6"/>',
  chevronRight: '<polyline points="9 18 15 12 9 6"/>',
  checkCircle: '<path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/>',
  alertCircle: '<circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/>',
  info: '<circle cx="12" cy="12" r="10"/><line x1="12" y1="16" x2="12" y2="12"/><line x1="12" y1="8" x2="12.01" y2="8"/>',
  xCircle: '<circle cx="12" cy="12" r="10"/><line x1="15" y1="9" x2="9" y2="15"/><line x1="9" y1="9" x2="15" y2="15"/>',
  clock: '<circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>',
  calendar: '<rect x="3" y="4" width="18" height="18" rx="2" ry="2"/><line x1="16" y1="2" x2="16" y2="6"/><line x1="8" y1="2" x2="8" y2="6"/><line x1="3" y1="10" x2="21" y2="10"/>',
  // Money
  cash: '<rect x="2" y="6" width="20" height="12" rx="2"/><circle cx="12" cy="12" r="2"/><path d="M6 12h.01M18 12h.01"/>',
  creditCard: '<rect x="1" y="4" width="22" height="16" rx="2" ry="2"/><line x1="1" y1="10" x2="23" y2="10"/>',
  dollarSign: '<line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"/>',
  trendingUp: '<polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/>',
  trendingDown: '<polyline points="23 18 13.5 8.5 8.5 13.5 1 6"/><polyline points="17 18 23 18 23 12"/>',
  // Products
  tag: '<path d="M20.59 13.41 13.42 20.58a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"/><line x1="7" y1="7" x2="7.01" y2="7"/>',
  barcode: '<path d="M3 5v14M8 5v14M12 5v14M17 5v14M21 5v14"/>',
  // People
  user: '<path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>',
  userPlus: '<path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="8.5" cy="7" r="4"/><line x1="20" y1="8" x2="20" y2="14"/><line x1="23" y1="11" x2="17" y2="11"/>',
  phone: '<path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/>',
  mail: '<path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/>',
  mapPin: '<path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/>',
  // Other
  logIn: '<path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4"/><polyline points="10 17 15 12 10 7"/><line x1="15" y1="12" x2="3" y2="12"/>',
  logOut: '<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" y1="12" x2="9" y2="12"/>',
  grid: '<rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/>',
  list: '<line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/>',
  receipt: '<path d="M4 2v20l2-1 2 1 2-1 2 1 2-1 2 1 2-1 2 1V2l-2 1-2-1-2 1-2-1-2 1-2-1-2 1z"/><line x1="8" y1="8" x2="16" y2="8"/><line x1="8" y1="12" x2="16" y2="12"/><line x1="8" y1="16" x2="12" y2="16"/>',
  shoppingBag: '<path d="M6 2 3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z"/><line x1="3" y1="6" x2="21" y2="6"/><path d="M16 10a4 4 0 0 1-8 0"/>',
  award: '<circle cx="12" cy="8" r="7"/><polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88"/>',
  image: '<rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/>',
};

/**
 * إنشاء أيقونة SVG
 */
function icon(name, size, sw) {
  size = size || 20;
  sw = sw || 2;
  const inner = ICONS[name] || '';
  return '<svg xmlns="http://www.w3.org/2000/svg" width="' + size + '" height="' + size + '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="' + sw + '" stroke-linecap="round" stroke-linejoin="round">' + inner + '</svg>';
}

/* =========================================================================
   TRANSLATIONS
   ========================================================================= */
const TRANSLATIONS = {
  ar: {
    appName: "مَتْجَرِي POS", appTag: "نظام نقطة البيع",
    search: "ابحث", save: "حفظ", cancel: "الغاء", delete: "حذف", edit: "تعديل", add: "اضافة",
    close: "اغلاق", confirm: "تأكيد", yes: "نعم", no: "لا", back: "رجوع", next: "التالي",
    all: "الكل", none: "لا شيء", loading: "جاري التحميل", noData: "لا توجد بيانات",
    noResults: "لا توجد نتائج", required: "مطلوب", optional: "اختياري",
    areYouSure: "هل انت متأكد",
    today: "اليوم", yesterday: "امس", thisWeek: "هذا الاسبوع", thisMonth: "هذا الشهر",
    total: "الاجمالي", subtotal: "المجموع الفرعي", discount: "الخصم", tax: "الضريبة",
    grandTotal: "الاجمالي النهائي", netProfit: "الربح الصافي",
    qty: "الكمية", price: "السعر", amount: "المبلغ", status: "الحالة",
    date: "التاريخ", time: "الوقت", actions: "اجراءات",
    navHome: "الرئيسية", navPOS: "نقطة البيع", navProducts: "المخزون",
    navCustomers: "العملاء", navSuppliers: "الموردون", navCash: "الخزينة",
    navExpenses: "المصاريف", navReports: "التقارير", navUsers: "المستخدمون",
    navSettings: "الاعدادات", navBackup: "النسخ الاحتياطي", navLog: "سجل النشاط",
    greeting: "مرحبا", greetingMorning: "صباح الخير", greetingEvening: "مساء الخير",
    dashboardSub: "نظرة على اداء متجرك",
    cashBalance: "رصيد الخزينة", todaySales: "مبيعات اليوم", todayExpenses: "مصاريف اليوم",
    productsCount: "عدد المنتجات", lowStockAlert: "منتجات على وشك النفاد",
    lowStockDesc: "تحتاج اعادة تعبئة",
    quickAccess: "الادارة السريعة", recentSales: "آخر المبيعات", viewAll: "عرض الكل",
    posTitle: "نقطة البيع", posSub: "اختر المنتجات واتمم البيع",
    cartEmpty: "السلة فارغة", cartEmptyDesc: "ابحث عن منتج وابدأ البيع",
    cartItems: "منتج", searchProduct: "ابحث بالاسم او الباركود",
    productNotFound: "لم يتم العثور على منتج", addToCart: "اضف للسلة",
    outOfStock: "نفد المخزون", onlyXLeft: "متبقي فقط",
    paymentMethod: "طريقة الدفع", cash: "نقدي", credit: "بطاقة",
    completeSale: "اتمام البيع", newSale: "بيع جديد", clearCart: "تفريغ السلة",
    salesLog: "سجل المبيعات", cartCleared: "تم تفريغ السلة",
    saleCompleted: "تم البيع بنجاح", insufficientStock: "الكمية غير كافية",
    removeFromCart: "حذف من السلة", customer: "العميل", walkInCustomer: "عميل عابر",
    selectCustomer: "اختر العميل",
    productsTitle: "المخزون", productsSub: "إدارة المنتجات والكميات",
    addProduct: "اضافة منتج", editProduct: "تعديل منتج",
    productName: "اسم المنتج", productSKU: "الرمز SKU", productBarcode: "الباركود",
    productCategory: "الفئة", productPrice: "سعر البيع", productCost: "سعر التكلفة",
    productStock: "الكمية", productMinStock: "الحد الادنى", productUnit: "الوحدة",
    productDescription: "الوصف", productSaved: "تم حفظ المنتج",
    productDeleted: "تم حذف المنتج", product: "المنتج",
    inStock: "متوفر", lowStock: "منخفض", outStock: "نفد",
    categoryAll: "كل الفئات", filterStatus: "تصفية بالحالة",
    sortBy: "ترتيب حسب", sortName: "الاسم", sortPrice: "السعر",
    sortStock: "الكمية", sortDate: "التاريخ",
    customersTitle: "العملاء", customersSub: "إدارة العملاء والديون",
    addCustomer: "اضافة عميل", editCustomer: "تعديل عميل",
    customerName: "اسم العميل", customerPhone: "الهاتف", customerEmail: "البريد",
    customerAddress: "العنوان", customerNotes: "ملاحظات",
    customerDebt: "الدين", customerBalance: "الرصيد",
    customerSaved: "تم حفظ العميل", customerDeleted: "تم حذف العميل",
    customerDetails: "تفاصيل العميل", customerHasDebt: "لديه دين",
    totalPurchases: "اجمالي المشتريات", purchaseCount: "عدد المشتريات",
    lastPurchase: "آخر شراء", payDebt: "سداد الدين", debtPaid: "تم السداد",
    noDebt: "لا يوجد دين",
    suppliersTitle: "الموردون", suppliersSub: "إدارة الموردين واوامر الشراء",
    addSupplier: "اضافة مورد", editSupplier: "تعديل مورد",
    supplierName: "اسم المورد", supplierCompany: "الشركة",
    supplierPhone: "الهاتف", supplierEmail: "البريد",
    supplierSaved: "تم حفظ المورد", supplierDeleted: "تم حذف المورد",
    supplierOwed: "المبلغ المستحق", paySupplier: "سداد للمورد",
    cashTitle: "الخزينة", cashSub: "إدارة النقدية والحركات",
    currentBalance: "الرصيد الحالي", addCash: "ايداع", withdrawCash: "سحب",
    cashAdded: "تم الايداع", cashWithdrawn: "تم السحب",
    cashIn: "إيداع", cashOut: "سحب", saleIncome: "ارباح المبيعات",
    expenseOut: "مصاريف", customerPayment: "دفعة من عميل",
    supplierPayment: "دفعة لمورد", openingBalance: "الرصيد الافتتاحي",
    cashMovements: "حركات الخزينة", balanceAfter: "الرصيد بعد",
    movementReason: "السبب", insufficientCash: "الرصيد غير كاف",
    expensesTitle: "المصاريف", expensesSub: "تسجيل ومتابعة المصاريف",
    addExpense: "اضافة مصروف", editExpense: "تعديل مصروف",
    expenseName: "اسم المصروف", expenseAmount: "المبلغ",
    expenseCategory: "التصنيف", expenseDate: "التاريخ", expenseNotes: "ملاحظات",
    expenseSaved: "تم حفظ المصروف", expenseDeleted: "تم حذف المصروف",
    expenseAdded: "تم تسجيل المصروف",
    categoryRent: "ايجار", categorySalaries: "رواتب", categoryUtilities: "فواتير",
    categoryTransport: "نقل", categoryMarketing: "تسويق", categorySupplies: "مستلزمات",
    categoryMaintenance: "صيانة", categoryOther: "اخرى",
    totalExpenses: "اجمالي المصاريف",
    reportsTitle: "التقارير", reportsSub: "احصائيات واداء المتجر",
    reportSales: "المبيعات", reportProfit: "الارباح", reportProducts: "المنتجات",
    reportCustomers: "العملاء", reportExpenses: "المصاريف", reportCash: "الخزينة",
    todayRevenue: "ايراد اليوم", todayProfit: "ربح اليوم",
    weekRevenue: "ايراد الاسبوع", monthRevenue: "ايراد الشهر",
    yearRevenue: "ايراد السنة", profitMargin: "هامش الربح",
    topProducts: "افضل المنتجات", topCustomers: "افضل العملاء",
    salesChart: "رسم بياني للمبيعات", dailySales: "المبيعات اليومية",
    monthlySales: "المبيعات الشهرية", avgTicket: "متوسط الفاتورة",
    totalSales: "اجمالي المبيعات", salesCount: "عدد الفواتير",
    usersTitle: "المستخدمون", usersSub: "إدارة المستخدمين والصلاحيات",
    addUser: "اضافة مستخدم", editUser: "تعديل مستخدم",
    userName: "الاسم الكامل", userUsername: "اسم الدخول", userPassword: "كلمة المرور",
    userRole: "الصلاحية", roleAdmin: "مدير", roleSeller: "بائع", roleViewer: "مشاهد",
    userActive: "نشط", userInactive: "معطل", userSaved: "تم حفظ المستخدم",
    userDeleted: "تم حذف المستخدم", lastLogin: "آخر دخول", never: "لم يسجل",
    settingsTitle: "الاعدادات", settingsSub: "تخصيص النظام والمتجر",
    generalSettings: "عام", storeSettings: "المتجر", appearanceSettings: "المظهر",
    backupSettings: "النسخ الاحتياطي",
    language: "اللغة", theme: "المظهر", darkMode: "الوضع الليلي", lightMode: "الوضع النهاري",
    storeName: "اسم المتجر", storeTagline: "الشعار", storePhone: "الهاتف",
    storeEmail: "البريد", storeAddress: "العنوان", storeRC: "السجل التجاري",
    storeNIF: "الرقم الجبائي", storeLogo: "الشعار", uploadLogo: "رفع شعار",
    removeLogo: "حذف الشعار", primaryColor: "اللون الاساسي",
    storeCurrency: "العملة", taxRate: "نسبة الضريبة",
    settingsSaved: "تم حفظ الاعدادات",
    resetData: "مسح كل البيانات", resetDataConfirm: "سيتم مسح كل البيانات نهائيا",
    resetDone: "تم مسح البيانات",
    exportBackup: "تصدير نسخة احتياطية", importBackup: "استيراد نسخة احتياطية",
    backupExported: "تم تصدير النسخة", backupImported: "تم استيراد النسخة",
    backupInvalid: "الملف غير صالح", backupConfirm: "سيتم استبدال كل البيانات الحالية",
    logTitle: "سجل النشاط", logSub: "آخر العمليات",
    logSale: "عملية بيع", logProductAdd: "اضافة منتج", logProductEdit: "تعديل منتج",
    logProductDelete: "حذف منتج", logCustomerAdd: "اضافة عميل",
    logSupplierAdd: "اضافة مورد", logCashIn: "إيداع نقدي", logCashOut: "سحب نقدي",
    logExpense: "مصروف", logClear: "تفريغ السجل", logCleared: "تم تفريغ السجل",
    notifications: "الاشعارات", noNotifications: "لا توجد اشعارات",
    markAllRead: "تعليم الكل كمقروء",
    notifLowStock: "منتج على وشك النفاد", notifOutStock: "منتج نفد من المخزون",
    notifCustomerDebt: "دين عميل متاخر", notifSupplierOwed: "مبلغ مستحق لمورد",
    notifDayEnd: "تقرير نهاية اليوم",
    invoice: "فاتورة", invoiceNo: "رقم الفاتورة", invoiceDate: "تاريخ الفاتورة",
    invoiceCustomer: "العميل", invoiceSeller: "البائع", invoiceProduct: "المنتج",
    invoiceQty: "الكمية", invoicePrice: "السعر", invoiceTotal: "الاجمالي",
    invoicePaid: "مدفوع", invoicePending: "معلق",
    invoiceThanks: "شكرا لتعاملكم معنا",
    printInvoice: "طباعة الفاتورة", shareInvoice: "مشاركة الفاتورة",
    savedSuccessfully: "تم الحفظ بنجاح", deletedSuccessfully: "تم الحذف بنجاح",
    updatedSuccessfully: "تم التحديث", errorOccurred: "حدث خطا",
    networkError: "خطا في الاتصال", fillRequired: "املأ كل الحقول المطلوبة",
    invalidValue: "قيمة غير صالحة", noPermission: "لا تملك صلاحية",
    loggedOut: "تم تسجيل الخروج", loggedIn: "تم تسجيل الدخول",
    copied: "تم النسخ", printReady: "جاهز للطباعة",
    unitPiece: "قطعة", unitKg: "كغ", unitLiter: "لتر",
    unitBox: "علبة", unitPack: "حزمة", unitMeter: "متر",
    loginTitle: "سجّل دخولك للمتابعة", loginBtn: "دخول",
    backupTitle: "النسخ الاحتياطي", backupSub: "احفظ نسخة من بياناتك او استعدها",
  },
  en: {
    appName: "MY STORE POS", appTag: "Point of Sale System",
    search: "Search", save: "Save", cancel: "Cancel", delete: "Delete", edit: "Edit", add: "Add",
    close: "Close", confirm: "Confirm", yes: "Yes", no: "No", back: "Back", next: "Next",
    all: "All", none: "None", loading: "Loading", noData: "No data", noResults: "No results",
    required: "Required", optional: "Optional", areYouSure: "Are you sure",
    today: "Today", yesterday: "Yesterday", thisWeek: "This week", thisMonth: "This month",
    total: "Total", subtotal: "Subtotal", discount: "Discount", tax: "Tax",
    grandTotal: "Grand Total", netProfit: "Net Profit",
    qty: "Qty", price: "Price", amount: "Amount", status: "Status",
    date: "Date", time: "Time", actions: "Actions",
    navHome: "Home", navPOS: "Point of Sale", navProducts: "Inventory",
    navCustomers: "Customers", navSuppliers: "Suppliers", navCash: "Cash Register",
    navExpenses: "Expenses", navReports: "Reports", navUsers: "Users",
    navSettings: "Settings", navBackup: "Backup", navLog: "Activity Log",
    greeting: "Hello", greetingMorning: "Good morning", greetingEvening: "Good evening",
    dashboardSub: "Your store performance overview",
    cashBalance: "Cash Balance", todaySales: "Today's Sales", todayExpenses: "Today's Expenses",
    productsCount: "Products Count", lowStockAlert: "Low Stock Products",
    lowStockDesc: "Need restocking", quickAccess: "Quick Access",
    recentSales: "Recent Sales", viewAll: "View All",
    posTitle: "Point of Sale", posSub: "Select products and complete sale",
    cartEmpty: "Cart is empty", cartEmptyDesc: "Search for a product to start selling",
    cartItems: "items", searchProduct: "Search by name or barcode",
    productNotFound: "Product not found", addToCart: "Add to cart",
    outOfStock: "Out of stock", onlyXLeft: "Only left",
    paymentMethod: "Payment Method", cash: "Cash", credit: "Card",
    completeSale: "Complete Sale", newSale: "New Sale", clearCart: "Clear Cart",
    salesLog: "Sales Log", cartCleared: "Cart cleared",
    saleCompleted: "Sale completed", insufficientStock: "Insufficient stock",
    removeFromCart: "Remove", customer: "Customer", walkInCustomer: "Walk-in",
    selectCustomer: "Select Customer",
    productsTitle: "Inventory", productsSub: "Manage products and stock",
    addProduct: "Add Product", editProduct: "Edit Product",
    productName: "Product Name", productSKU: "SKU", productBarcode: "Barcode",
    productCategory: "Category", productPrice: "Sale Price", productCost: "Cost Price",
    productStock: "Stock", productMinStock: "Min Stock", productUnit: "Unit",
    productDescription: "Description", productSaved: "Product saved",
    productDeleted: "Product deleted", product: "Product",
    inStock: "In Stock", lowStock: "Low", outStock: "Out",
    categoryAll: "All Categories", filterStatus: "Filter status",
    sortBy: "Sort by", sortName: "Name", sortPrice: "Price",
    sortStock: "Stock", sortDate: "Date",
    customersTitle: "Customers", customersSub: "Manage customers and debts",
    addCustomer: "Add Customer", editCustomer: "Edit Customer",
    customerName: "Customer Name", customerPhone: "Phone", customerEmail: "Email",
    customerAddress: "Address", customerNotes: "Notes",
    customerDebt: "Debt", customerBalance: "Balance",
    customerSaved: "Customer saved", customerDeleted: "Customer deleted",
    customerDetails: "Customer Details", customerHasDebt: "Has debt",
    totalPurchases: "Total Purchases", purchaseCount: "Purchase Count",
    lastPurchase: "Last Purchase", payDebt: "Pay Debt", debtPaid: "Debt paid",
    noDebt: "No debt",
    suppliersTitle: "Suppliers", suppliersSub: "Manage suppliers and orders",
    addSupplier: "Add Supplier", editSupplier: "Edit Supplier",
    supplierName: "Supplier Name", supplierCompany: "Company",
    supplierPhone: "Phone", supplierEmail: "Email",
    supplierSaved: "Supplier saved", supplierDeleted: "Supplier deleted",
    supplierOwed: "Amount Owed", paySupplier: "Pay Supplier",
    cashTitle: "Cash Register", cashSub: "Manage cash and movements",
    currentBalance: "Current Balance", addCash: "Deposit", withdrawCash: "Withdraw",
    cashAdded: "Cash added", cashWithdrawn: "Cash withdrawn",
    cashIn: "Deposit", cashOut: "Withdrawal", saleIncome: "Sale Income",
    expenseOut: "Expense", customerPayment: "Customer Payment",
    supplierPayment: "Supplier Payment", openingBalance: "Opening Balance",
    cashMovements: "Cash Movements", balanceAfter: "Balance After",
    movementReason: "Reason", insufficientCash: "Insufficient balance",
    expensesTitle: "Expenses", expensesSub: "Track and manage expenses",
    addExpense: "Add Expense", editExpense: "Edit Expense",
    expenseName: "Expense Name", expenseAmount: "Amount",
    expenseCategory: "Category", expenseDate: "Date", expenseNotes: "Notes",
    expenseSaved: "Expense saved", expenseDeleted: "Expense deleted",
    expenseAdded: "Expense recorded",
    categoryRent: "Rent", categorySalaries: "Salaries", categoryUtilities: "Utilities",
    categoryTransport: "Transport", categoryMarketing: "Marketing", categorySupplies: "Supplies",
    categoryMaintenance: "Maintenance", categoryOther: "Other",
    totalExpenses: "Total Expenses",
    reportsTitle: "Reports", reportsSub: "Store statistics",
    reportSales: "Sales", reportProfit: "Profit", reportProducts: "Products",
    reportCustomers: "Customers", reportExpenses: "Expenses", reportCash: "Cash",
    todayRevenue: "Today Revenue", todayProfit: "Today Profit",
    weekRevenue: "Week Revenue", monthRevenue: "Month Revenue",
    yearRevenue: "Year Revenue", profitMargin: "Profit Margin",
    topProducts: "Top Products", topCustomers: "Top Customers",
    salesChart: "Sales Chart", dailySales: "Daily Sales",
    monthlySales: "Monthly Sales", avgTicket: "Average Ticket",
    totalSales: "Total Sales", salesCount: "Invoice Count",
    usersTitle: "Users", usersSub: "Manage users and permissions",
    addUser: "Add User", editUser: "Edit User",
    userName: "Full Name", userUsername: "Username", userPassword: "Password",
    userRole: "Role", roleAdmin: "Admin", roleSeller: "Seller", roleViewer: "Viewer",
    userActive: "Active", userInactive: "Inactive", userSaved: "User saved",
    userDeleted: "User deleted", lastLogin: "Last Login", never: "Never",
    settingsTitle: "Settings", settingsSub: "Customize system and store",
    generalSettings: "General", storeSettings: "Store", appearanceSettings: "Appearance",
    backupSettings: "Backup",
    language: "Language", theme: "Theme", darkMode: "Dark Mode", lightMode: "Light Mode",
    storeName: "Store Name", storeTagline: "Tagline", storePhone: "Phone",
    storeEmail: "Email", storeAddress: "Address", storeRC: "Trade Register",
    storeNIF: "Tax ID", storeLogo: "Logo", uploadLogo: "Upload Logo",
    removeLogo: "Remove Logo", primaryColor: "Primary Color",
    storeCurrency: "Currency", taxRate: "Tax Rate",
    settingsSaved: "Settings saved",
    resetData: "Reset All Data", resetDataConfirm: "All data will be deleted",
    resetDone: "Data cleared",
    exportBackup: "Export Backup", importBackup: "Import Backup",
    backupExported: "Backup exported", backupImported: "Backup imported",
    backupInvalid: "Invalid file", backupConfirm: "All current data will be replaced",
    logTitle: "Activity Log", logSub: "Recent operations",
    logSale: "Sale", logProductAdd: "Product added", logProductEdit: "Product edited",
    logProductDelete: "Product deleted", logCustomerAdd: "Customer added",
    logSupplierAdd: "Supplier added", logCashIn: "Cash deposit", logCashOut: "Cash withdrawal",
    logExpense: "Expense", logClear: "Clear Log", logCleared: "Log cleared",
    notifications: "Notifications", noNotifications: "No notifications",
    markAllRead: "Mark all read",
    notifLowStock: "Product low stock", notifOutStock: "Product out of stock",
    notifCustomerDebt: "Customer debt", notifSupplierOwed: "Amount owed to supplier",
    notifDayEnd: "End of day report",
    invoice: "Invoice", invoiceNo: "Invoice No", invoiceDate: "Date",
    invoiceCustomer: "Customer", invoiceSeller: "Seller", invoiceProduct: "Product",
    invoiceQty: "Qty", invoicePrice: "Price", invoiceTotal: "Total",
    invoicePaid: "Paid", invoicePending: "Pending",
    invoiceThanks: "Thank you for your business",
    printInvoice: "Print Invoice", shareInvoice: "Share Invoice",
    savedSuccessfully: "Saved successfully", deletedSuccessfully: "Deleted successfully",
    updatedSuccessfully: "Updated", errorOccurred: "An error occurred",
    networkError: "Network error", fillRequired: "Fill all required fields",
    invalidValue: "Invalid value", noPermission: "No permission",
    loggedOut: "Logged out", loggedIn: "Logged in",
    copied: "Copied", printReady: "Ready to print",
    unitPiece: "Piece", unitKg: "Kg", unitLiter: "Liter",
    unitBox: "Box", unitPack: "Pack", unitMeter: "Meter",
    loginTitle: "Sign in to continue", loginBtn: "Sign in",
    backupTitle: "Backup", backupSub: "Save or restore your data",
  },
  fr: {
    appName: "MA BOUTIQUE POS", appTag: "Point de Vente",
    search: "Rechercher", save: "Enregistrer", cancel: "Annuler", delete: "Supprimer",
    edit: "Modifier", add: "Ajouter", close: "Fermer", confirm: "Confirmer",
    yes: "Oui", no: "Non", back: "Retour", next: "Suivant",
    all: "Tout", none: "Aucun", loading: "Chargement", noData: "Aucune donnee",
    noResults: "Aucun resultat", required: "Obligatoire", optional: "Optionnel",
    areYouSure: "Etes-vous sur",
    today: "Aujourd'hui", yesterday: "Hier", thisWeek: "Cette semaine", thisMonth: "Ce mois",
    total: "Total", subtotal: "Sous-total", discount: "Remise", tax: "TVA",
    grandTotal: "Total General", netProfit: "Benefice Net",
    qty: "Qte", price: "Prix", amount: "Montant", status: "Statut",
    date: "Date", time: "Heure", actions: "Actions",
    navHome: "Accueil", navPOS: "Point de Vente", navProducts: "Stock",
    navCustomers: "Clients", navSuppliers: "Fournisseurs", navCash: "Caisse",
    navExpenses: "Depenses", navReports: "Rapports", navUsers: "Utilisateurs",
    navSettings: "Parametres", navBackup: "Sauvegarde", navLog: "Journal",
    greeting: "Bonjour", greetingMorning: "Bonjour", greetingEvening: "Bonsoir",
    dashboardSub: "Apercu de votre boutique",
    cashBalance: "Solde de Caisse", todaySales: "Ventes du Jour", todayExpenses: "Depenses du Jour",
    productsCount: "Nombre de Produits", lowStockAlert: "Produits en Stock Faible",
    lowStockDesc: "Reapprovisionnement necessaire", quickAccess: "Acces Rapide",
    recentSales: "Ventes Recentes", viewAll: "Voir Tout",
    posTitle: "Point de Vente", posSub: "Selectionnez et finalisez la vente",
    cartEmpty: "Panier vide", cartEmptyDesc: "Recherchez un produit",
    cartItems: "articles", searchProduct: "Nom ou code-barres",
    productNotFound: "Produit introuvable", addToCart: "Ajouter",
    outOfStock: "Rupture de stock", onlyXLeft: "Reste seulement",
    paymentMethod: "Mode de Paiement", cash: "Especes", credit: "Carte",
    completeSale: "Finaliser", newSale: "Nouvelle Vente", clearCart: "Vider",
    salesLog: "Historique", cartCleared: "Panier vide",
    saleCompleted: "Vente effectuee", insufficientStock: "Stock insuffisant",
    removeFromCart: "Retirer", customer: "Client", walkInCustomer: "Client Passager",
    selectCustomer: "Choisir Client",
    productsTitle: "Stock", productsSub: "Gerer les produits",
    addProduct: "Ajouter Produit", editProduct: "Modifier Produit",
    productName: "Nom", productSKU: "SKU", productBarcode: "Code-barres",
    productCategory: "Categorie", productPrice: "Prix Vente", productCost: "Cout",
    productStock: "Stock", productMinStock: "Stock Min", productUnit: "Unite",
    productDescription: "Description", productSaved: "Produit enregistre",
    productDeleted: "Produit supprime", product: "Produit",
    inStock: "En Stock", lowStock: "Faible", outStock: "Rupture",
    categoryAll: "Toutes Categories", filterStatus: "Filtrer par statut",
    sortBy: "Trier par", sortName: "Nom", sortPrice: "Prix",
    sortStock: "Stock", sortDate: "Date",
    customersTitle: "Clients", customersSub: "Gerer les clients",
    addCustomer: "Ajouter Client", editCustomer: "Modifier Client",
    customerName: "Nom", customerPhone: "Telephone", customerEmail: "Email",
    customerAddress: "Adresse", customerNotes: "Notes",
    customerDebt: "Dette", customerBalance: "Solde",
    customerSaved: "Client enregistre", customerDeleted: "Client supprime",
    customerDetails: "Details Client", customerHasDebt: "A une dette",
    totalPurchases: "Total Achats", purchaseCount: "Nombre Achats",
    lastPurchase: "Dernier Achat", payDebt: "Payer Dette", debtPaid: "Dette payee",
    noDebt: "Aucune dette",
    suppliersTitle: "Fournisseurs", suppliersSub: "Gerer les fournisseurs",
    addSupplier: "Ajouter Fournisseur", editSupplier: "Modifier Fournisseur",
    supplierName: "Nom", supplierCompany: "Societe",
    supplierPhone: "Telephone", supplierEmail: "Email",
    supplierSaved: "Fournisseur enregistre", supplierDeleted: "Fournisseur supprime",
    supplierOwed: "Montant Du", paySupplier: "Payer Fournisseur",
    cashTitle: "Caisse", cashSub: "Gerer les mouvements",
    currentBalance: "Solde Actuel", addCash: "Depot", withdrawCash: "Retrait",
    cashAdded: "Depot effectue", cashWithdrawn: "Retrait effectue",
    cashIn: "Depot", cashOut: "Retrait", saleIncome: "Vente",
    expenseOut: "Depense", customerPayment: "Paiement Client",
    supplierPayment: "Paiement Fournisseur", openingBalance: "Solde Initial",
    cashMovements: "Mouvements", balanceAfter: "Solde Apres",
    movementReason: "Motif", insufficientCash: "Solde insuffisant",
    expensesTitle: "Depenses", expensesSub: "Suivre les depenses",
    addExpense: "Ajouter Depense", editExpense: "Modifier Depense",
    expenseName: "Nom", expenseAmount: "Montant",
    expenseCategory: "Categorie", expenseDate: "Date", expenseNotes: "Notes",
    expenseSaved: "Depense enregistree", expenseDeleted: "Depense supprimee",
    expenseAdded: "Depense enregistree",
    categoryRent: "Loyer", categorySalaries: "Salaires", categoryUtilities: "Factures",
    categoryTransport: "Transport", categoryMarketing: "Marketing", categorySupplies: "Fournitures",
    categoryMaintenance: "Maintenance", categoryOther: "Autre",
    totalExpenses: "Total Depenses",
    reportsTitle: "Rapports", reportsSub: "Statistiques",
    reportSales: "Ventes", reportProfit: "Profits", reportProducts: "Produits",
    reportCustomers: "Clients", reportExpenses: "Depenses", reportCash: "Caisse",
    todayRevenue: "Revenu du Jour", todayProfit: "Profit du Jour",
    weekRevenue: "Revenu Semaine", monthRevenue: "Revenu Mois",
    yearRevenue: "Revenu Annee", profitMargin: "Marge",
    topProducts: "Top Produits", topCustomers: "Top Clients",
    salesChart: "Graphique des Ventes", dailySales: "Ventes Quotidiennes",
    monthlySales: "Ventes Mensuelles", avgTicket: "Ticket Moyen",
    totalSales: "Total Ventes", salesCount: "Nombre Factures",
    usersTitle: "Utilisateurs", usersSub: "Gerer les utilisateurs",
    addUser: "Ajouter Utilisateur", editUser: "Modifier Utilisateur",
    userName: "Nom Complet", userUsername: "Identifiant", userPassword: "Mot de Passe",
    userRole: "Role", roleAdmin: "Admin", roleSeller: "Vendeur", roleViewer: "Observateur",
    userActive: "Actif", userInactive: "Inactif", userSaved: "Utilisateur enregistre",
    userDeleted: "Utilisateur supprime", lastLogin: "Derniere Connexion", never: "Jamais",
    settingsTitle: "Parametres", settingsSub: "Personnaliser le systeme",
    generalSettings: "General", storeSettings: "Boutique", appearanceSettings: "Apparence",
    backupSettings: "Sauvegarde",
    language: "Langue", theme: "Theme", darkMode: "Mode Sombre", lightMode: "Mode Clair",
    storeName: "Nom Boutique", storeTagline: "Slogan", storePhone: "Telephone",
    storeEmail: "Email", storeAddress: "Adresse", storeRC: "RC",
    storeNIF: "NIF", storeLogo: "Logo", uploadLogo: "Telecharger Logo",
    removeLogo: "Supprimer Logo", primaryColor: "Couleur Principale",
    storeCurrency: "Devise", taxRate: "Taux TVA",
    settingsSaved: "Parametres enregistres",
    resetData: "Reinitialiser", resetDataConfirm: "Toutes les donnees seront supprimees",
    resetDone: "Donnees effacees",
    exportBackup: "Exporter Sauvegarde", importBackup: "Importer Sauvegarde",
    backupExported: "Sauvegarde exportee", backupImported: "Sauvegarde importee",
    backupInvalid: "Fichier invalide", backupConfirm: "Toutes les donnees seront remplacees",
    logTitle: "Journal", logSub: "Operations recentes",
    logSale: "Vente", logProductAdd: "Produit ajoute", logProductEdit: "Produit modifie",
    logProductDelete: "Produit supprime", logCustomerAdd: "Client ajoute",
    logSupplierAdd: "Fournisseur ajoute", logCashIn: "Depot", logCashOut: "Retrait",
    logExpense: "Depense", logClear: "Vider Journal", logCleared: "Journal vide",
    notifications: "Notifications", noNotifications: "Aucune notification",
    markAllRead: "Tout marquer lu",
    notifLowStock: "Stock faible", notifOutStock: "Rupture de stock",
    notifCustomerDebt: "Dette client", notifSupplierOwed: "Montant du fournisseur",
    notifDayEnd: "Rapport de fin de journee",
    invoice: "Facture", invoiceNo: "Facture No", invoiceDate: "Date",
    invoiceCustomer: "Client", invoiceSeller: "Vendeur", invoiceProduct: "Produit",
    invoiceQty: "Qte", invoicePrice: "Prix", invoiceTotal: "Total",
    invoicePaid: "Payee", invoicePending: "En Attente",
    invoiceThanks: "Merci de votre visite",
    printInvoice: "Imprimer Facture", shareInvoice: "Partager Facture",
    savedSuccessfully: "Enregistre", deletedSuccessfully: "Supprime",
    updatedSuccessfully: "Mis a jour", errorOccurred: "Erreur survenue",
    networkError: "Erreur reseau", fillRequired: "Remplir tous les champs",
    invalidValue: "Valeur invalide", noPermission: "Pas de permission",
    loggedOut: "Deconnecte", loggedIn: "Connecte",
    copied: "Copie", printReady: "Pret a imprimer",
    unitPiece: "Piece", unitKg: "Kg", unitLiter: "Litre",
    unitBox: "Boite", unitPack: "Pack", unitMeter: "Metre",
    loginTitle: "Connectez-vous pour continuer", loginBtn: "Se connecter",
    backupTitle: "Sauvegarde", backupSub: "Sauvegardez ou restaurez vos donnees",
  }
};